
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import constans.Constants;
import log.NovaLog;

import static org.junit.Assert.*;

public class AppTest {

    static NovaLog Log = NovaLog.generateLog(AppTest.class);

    @Test
    public void testLog() {
        Constants.MODE_DEBUG = false;
        System.out.println("NO DEBUG");
        Log.error("This is an error information.");
        Log.debug("This is an debug level information.");
        Log.info("This is an information.");
        Constants.MODE_DEBUG = true;
        System.out.println("DEBUG");
        Log.error("This is an error information.");
        Log.debug("This is an debug level information.");
        Log.info("This is an information.");
    }
}
